title: AC Docs
description: ActiveCampaign integration guides for solution engineers and developers

remote_theme: just-the-docs/just-the-docs

color_scheme: ac-dark
search_enabled: true
heading_anchors: true

logo: "/assets/images/ac-logo.svg"

aux_links:
  "View on GitHub":
    - "https://github.com/actest4test-sys/AC-Docs"

footer_content: "ActiveCampaign integration guides."

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
